### ISSUE TITLE
Crash from Google Play

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar-manager-android#4]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.traccar.manager/org.traccar.manager.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.mkdir()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2521)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
	at android.app.ActivityThread.access$800(ActivityThread.java:178)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5631)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.mkdir()' on a null object reference
	at maps.dz.o.a(Unknown Source)
	at maps.dg.e.a(Unknown Source)
	at maps.dg.p.a(Unknown Source)
	at maps.ei.ag.a(Unknown Source)
	at maps.ei.bu.a(Unknown Source)
	at maps.ei.n$1.a(Unknown Source)
	at maps.ei.n.a(Unknown Source)
	at com.google.android.gms.maps.internal.i$a.onTransact(:com.google.android.gms.alldynamite:107)
	at android.os.Binder.transact(Binder.java:385)
	at com.google.android.gms.maps.internal.IMapFragmentDelegate$zza$zza.onCreateView(Unknown Source)
	at com.google.android.gms.maps.SupportMapFragment$zza.onCreateView(Unknown Source)
	at com.google.android.gms.dynamic.zza$4.zzb(Unknown Source)
	at com.google.android.gms.dynamic.zza.zza(Unknown Source)
	at com.google.android.gms.dynamic.zza.onCreateView(Unknown Source)
	at com.google.android.gms.maps.SupportMapFragment.onCreateView(Unknown Source)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1244)
	at android.app.Activity.performStart(Activity.java:6108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2478)
	... 10 more
```

**Comment by deinlandel** [comment]
Apparently, this is a bug in google maps library which is somehow related to file storage. I am also very interested on how to work around this, as my app getting similar crash reports. =(

**Comment by tananaev** [comment]
I know. It's a bug in Google services library. Looks like it's going to be fixed in the next major release:

https://code.google.com/p/gmaps-api-issues/issues/detail?id=9021
